import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { Gavel, Scale, AlertTriangle, FileCheck, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="pt-32 pb-24 bg-bg-base min-h-screen relative overflow-hidden">
      <div className="absolute inset-0 topo-bg opacity-5 pointer-events-none" />
      
      <div className="max-w-4xl mx-auto px-6 relative z-10">
        <Link to="/" className="inline-flex items-center gap-2 text-primary hover:text-white transition-colors mb-8 font-mono text-sm uppercase tracking-widest">
          <ArrowLeft size={16} /> [ Back to Base ]
        </Link>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-black/20 dark:bg-white/5 border border-black/10 dark:border-white/10 p-12 rounded-[2rem] backdrop-blur-xl"
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary">
              <Gavel size={28} />
            </div>
            <div>
              <h1 className="font-display text-4xl font-bold">Terms of Service</h1>
              <p className="text-text-muted font-mono text-xs uppercase tracking-widest mt-1">Operational Protocol v4.2 // Legal Framework</p>
            </div>
          </div>

          <div className="prose prose-invert max-w-none space-y-8 text-text-base/80 leading-relaxed">
            <section>
              <h2 className="text-2xl font-display font-bold text-secondary mb-4 flex items-center gap-3">
                <Scale size={20} /> Acceptable Use
              </h2>
              <p>
                By accessing SpatioCore Tech systems, you agree to utilize our spatial intelligence tools solely for ethical, legal planning and data analysis. Any attempt to reverse-engineer satellite algorithms or infiltrate the SpatioCore grid is strictly forbidden.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold text-secondary mb-4 flex items-center gap-3">
                <FileCheck size={20} /> Service Availability
              </h2>
              <p>
                SpatioCore Tech provides "as-is" spatial data and consultation. While we strive for millimetric precision, orbital decay, atmospheric interference, and ground-level drift may affect live data feeds. We reserve the right to suspend data streams for sector maintenance.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold text-secondary mb-4 flex items-center gap-3">
                <AlertTriangle size={20} /> Liability Limits
              </h2>
              <p>
                SpatioCore Tech shall not be held liable for tectonic shifts, unforeseen environmental variances, or decisions made based on predictive modeling. All final ground decisions remain the responsibility of the client.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold text-secondary mb-4">Content Proprietary Rights</h2>
              <p>
                All topographic maps, spectral analysis reports, and customized GIS layers generated by SpatioCore Tech remain the intellectual property of SpatioCore Tech unless explicit transfer protocols are executed in the primary contract.
              </p>
            </section>

            <section className="pt-8 border-t border-white/10">
              <p className="text-xs text-text-muted font-mono italic">
                Execution of these terms is governed by the laws of Pakistan and International Spatial Protocols.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
